baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Smartphone Repair Ottawa'
url: 'https://smartphonerepairottawa.ca'

collections:
  services:
    output: true
    permalink: /services/:path/
  repairs:
    output: true
    permalink: /repairs/:path/
  unlocks:
    output: true
    permalink: /unlocks/:path/
  computer-repairs:
    output: true
    permalink: /computer-repairs/:path/
  shop:
    output: true
    permalink: /shop/:path/
  team:
    output: true
    permalink: /team/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true
  - scope:
      type: repairs
    values:
      layout: service
      bodyClass: page-service-single
  - scope:
      type: unlocks
    values:
      layout: service
      bodyClass: page-service-single
  - scope:
      type: computer-repairs
    values:
      layout: service
      bodyClass: page-service-single
  - scope:
      type: shop
    values:
      layout: service
      bodyClass: page-service-single

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: UA-21304201-11

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap
